---
title: "Lab 3A"
author: Joe Minton
date: 09/07/2020
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
options(max.print=1000)
```

```{r, eval=FALSE}
download.file(url = "https://ndownloader.figshare.com/files/2292169" , destfile = "data/portal_data.joined.csv")
```
```{r}
surveys <- read.csv("data/portal_data_joined.csv")
```

surveys

```{r}
head(surveys)
```
```{r}
view(surveys)
```

```{r}
str(surveys)
```

```{r}
names(surveys)
```
```{r, results = "hide"}
rownames(surveys)
```

```{r}
dim(surveys)
```


## Challenge Set 1
```{r}
 # class: data frame
 # how many rows: 34786, how many columns: 13
 # how many species: 48
```
   
```{r}
surveys[1, 1]
```

```{r}
surveys[1, 6]
```

```{r}
surveys[, 1]
```

```{r}
surveys[1]
```

```{r}
surveys[1:3, 7]
```

```{r}
surveys[3, ]
```

```{r}
head_surveys <- surveys[1:6, ]
```

```{r}
1:10
```

```{r}
10:1
```

```{r, result = "hide"}
surveys[, -1]
```

```{r}
surveys[-(7:34786), ]
```

```{r}
surveys["species_id"]
```

```{r}
surveys[, "species_id"]
```

```{r}
surveys[["species_id"]]
```

```{r}
surveys$species_id
```

## Challenge Set 2
```{r}
## 1.
surveys_200 <- surveys[200, ]
## 2
n_rows <- nrow(surveys)
surveys_last <- surveys[n_rows, ]
## 3
survey_middle <- surveys[n_rows / 2, ]
## 4
surveys_head <- surveys[-(7:n_rows), ]
```

```{r}
sex <- factor(c("male" , "female" , "female", "male"))
```

```{r}
levels(sex)
nlevels(sex)
```

```{r}
sex # current order
```

```{r}
sex <- factor(sex, levels = c("male" , "female"))
sex # after re-ordering
```

```{r}
as.character(sex)
```

```{r}
year_fct <- factor(c(1990, 1983, 1977, 1998, 1990))
as.numeric(year_fct)

as.numeric(as.character(year_fct))
as.numeric(levels(year_fct))[year_fct]
```

```{r}
## bar plot of the number of females and males captured during the experiment:

plot(as.factor(surveys$sex))
```

```{r}
sex <- factor(surveys$sex)
head(sex)
```

```{r}
levels(sex)
```

```{r}
levels(sex)[1] <- "undetermined"
levels(sex)
```

```{r}
head(sex)
```

## Challenge Set 3
```{r}
levels(sex)[2:3] <- c("female", "male")

sex <- factor(sex, levels = c("female", "male", "undetermined"))

plot(sex)
```

```{r}
## Compare the difference between our data read as `factor` vs `character`.

surveys <- read.csv("data/portal_data_joined.csv" , stringsAsFactors = TRUE)

str(surveys)
surveys <- read.csv("data/portal_data_joined.csv" , stringsAsFactors = FALSE)

str(surveys)
## Convert the column "plot_type" into a factor
surveys$plot_type <- factor(surveys$plot_type)
```

## Challenge Set 4
```{r}
## 1.
animal_data <- data.frame(
    animal = c("dog", "cat", "sea cucumber", "sea urchin"),
    
    feel = c("furry", "soft", "squishy", "spiny"),
    
    weight = c(45, 8, 1.1, 0.8))

## To fix the errors, quotation marks were placed around the animal names, an adjective to the feel for the cat, and commas were added to weight

## 2
country_climate <- data.frame(
  country = c("Canada", "Panama", "South Africa", "Australia"),
  
  climate = c("cold", "hot", "temperature", "hot/temperature"),
  
  temperature = c(10, 30, 18, 15),
  northern_hemisphere = c(TRUE, TRUE, FALSE, FALSE),
  
  has_kangaroo = c(FALSE, FALSE, FALSE, TRUE))

## To fix the issues, the quotes around 15 had to be removed for temperature and for the last false in northern_hempisphere. The last 1 in has_kangaroos had to be changed to true. Adding stringAsFactors = False would convert the factors into vectors.
```

```{r}
str(surveys)
```

```{r}
library("lubridate")
```

```{r}
my_date <- ymd("2015-01-01")
str(my_date)
```

```{r}
## sep indicates the character to use to separate each component

my_date <- ymd(paste("2015", "1", "1", sep = "-"))
str(my_date)
```

```{r, results = "hide"}
paste(surveys$year, surveys$month, surveys$day, sep ="-")
```

```{r}
ymd(paste(surveys$year, surveys$month, surveys$day, sep = "-"))
```

```{r}
surveys$date <- ymd(paste(surveys$year, surveys$month, surveys$day, sep = "-"))
```

```{r}
str(surveys)
```

```{r}
summary(surveys$date)
```

```{r}
missing_dates <- surveys[is.na(surveys$date), c("year", "month", "day")]

head(missing_dates)
```