---
title: "Lab 6: Data Maps and Interactive Graphs from the COVID-19 Reporting Data"
author: "Joe Minton"
date: "09/28/2020"
output: html_document
bibliography: data/references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Building Maps
```{r, echo = FALSE, include = FALSE}
library(tidyverse)
library(maps)
library(mapdata)
library(lubridate)
library(viridis)
library(wesanderson)
library(RColorBrewer)
library(plotly)
options(max.print=1000)
```

```{r, echo=FALSE, include=FALSE, message=FALSE}
## map of all coordinates in world 

daily_report <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-02-2020.csv")) %>% 
  rename(Long = "Long_") 
    
ggplot(daily_report, aes(x = Long, y = Lat, size = Confirmed/1000)) +
    borders("world", colour = NA, fill = "grey90") +
    theme_bw() +
    geom_point(shape = 21, color='purple', fill='purple', alpha = 0.5) +
    labs(title = 'World COVID-19 Confirmed cases',x = 'Long', y = 'Lat',
        size = "Cases (x1000))") +
    theme(legend.position = "right") +
    coord_fixed(ratio=1.5)
```

```{r, echo=FALSE, message=FALSE}
## focusing on 48 US states without territories, Alaska, Hawaii

daily_report <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-05-2020.csv")) %>% 
  rename(Long = "Long_") %>% 
  filter(Country_Region == "US") %>% 
  filter (!Province_State %in% c("Alaska","Hawaii", "American Samoa","Puerto Rico","Northern Mariana Islands", "Virgin Islands", "Recovered", "Guam", "Grand Princess", "District of Columbia", "Diamond Princess")) %>% 
  filter(Lat > 0)
ggplot(daily_report, aes(x = Long, y = Lat, size = Confirmed/1000)) +
    borders("state", colour = "black", fill = "grey90") +
    theme_bw() +
    geom_point(shape = 21, color='purple', fill='purple', alpha = 0.5) +
    labs(title = 'COVID-19 Confirmed Cases in the US', x = 'Long', y = 'Lat',
        size="Cases (x1000))") +
    theme(legend.position = "right") +
    coord_fixed(ratio=1.5)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
## example by Anisa Dhana
mybreaks <- c(1, 100, 1000, 10000, 10000)
ggplot(daily_report, aes(x = Long, y = Lat, size = Confirmed)) +
    borders("state", colour = "white", fill = "grey90") +
    geom_point(aes(x=Long, y=Lat, size=Confirmed, color=Confirmed),stroke=F, alpha=0.7) +
    scale_size_continuous(name="Cases", trans="log", range=c(1,7), breaks=mybreaks, labels = c("1-99", "100-999", "1,000-9,999", "10,000-99,999", "50,000+")) +
scale_color_viridis_c(option="viridis",name="Cases", trans="log", breaks=mybreaks, labels = c("1-99", "100-999", "1,000-9,999", "10,000-99,999", "50,000+"))  +
  
# Cleaning up the graph
  
theme_void() + 
    guides( colour = guide_legend()) +
    labs(title = "Anisa Dhana's lagout for COVID-19 Confirmed Cases in the US'") +
    theme(
      legend.position = "bottom",
      text = element_text(color = "#22211d"),
      plot.background = element_rect(fill = "#ffffff", color = NA), 
      panel.background = element_rect(fill = "#ffffff", color = NA), 
      legend.background = element_rect(fill = "#ffffff", color = NA)
    ) +
    coord_fixed(ratio=1.5)

# borders is used to defines areas in the map
```

## Mapping Data to Shapes
```{r, echo=FALSE, message=FALSE, results=FALSE, warning=FALSE}
daily_report <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-02-2020.csv")) %>% 
  rename(Long = "Long_") %>% 
  filter(Country_Region == "US") %>% 
  group_by(Province_State) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  mutate(Province_State = tolower(Province_State))

# load the US map data

us <- map_data("state")

# We need to join the us map data with our daily report to make one data frame/tibble

state_join <- left_join(us, daily_report, by = c("region" = "Province_State"))

# plot state map using different R color palettes

ggplot(data = us, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  
# Add data layer
  
  geom_polygon(data = state_join, aes(fill = Confirmed), color = "black") +
  scale_fill_gradientn(colours = 
                         wes_palette("Zissou1", 100, type = "continuous"),
                         trans = "log10") +
  labs(title = "COVID-19 Confirmed Cases in the US'")
```

```{r, echo=FALSE, message=FALSE, results=FALSE, warning=FALSE}
# looking at counties using RColorBrewer
# To display only colorblind-friendly brewer palettes, specify colorblindFriendly = TRUE as follows:
# display.brewer.all(colorblindFriendly = TRUE)
# Get and format covid report data

report_03_27_2020 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-02-2020.csv")) %>% 
  rename(Long = "Long_") %>% 
  unite(Key, Admin2, Province_State, sep = ".") %>% 
  group_by(Key) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  mutate(Key = tolower(Key))
dim(report_03_27_2020)

#get and format the map data

us <- map_data("state")
counties <- map_data("county") %>% 
  unite(Key, subregion, region, sep = ".", remove = FALSE)
 
# join the two tibbles

state_join <- left_join(counties, report_03_27_2020, by = c("Key"))

sum(is.name(state_join$Confirmed))

ggplot(data = us, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  borders("state", colour = "black") +
  geom_polygon(data = state_join, aes(fill = Confirmed)) +
  scale_fill_gradientn(colors = brewer.pal(n = 5, name = "PuRd"),
        breaks = c(1, 10, 100, 1000, 10000, 100000),
        trans = "log10", na.value = "White") +
  ggtitle("Number of Confirmed Cases by US County") +
  theme_bw() 
```

```{r, echo=FALSE, message=FALSE, results=FALSE, warning=FALSE}
# Looking at just Massachusetts

daily_report <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-02-2020.csv")) %>% 
  rename(Long = "Long_") %>% 
  filter(Province_State == "Massachusetts") %>% 
  group_by(Admin2) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  mutate(Admin2 = tolower(Admin2))

us <- map_data("state")
ma_us <- subset(us, region == "massachusetts")
counties <- map_data("county")
ma_county <- subset(counties, region == "massachusetts")
state_join <- left_join(ma_county, daily_report, by = c("subregion" = "Admin2")) 

# plot state map

ggplot(data = ma_county, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(data = state_join, aes(fill = Confirmed), color = "white") +
  scale_fill_gradientn(colors = brewer.pal(n = 5, name = "BuGn"), trans = "log10") +
  labs(title = "COVID-19 Confirmed Cases in Massachusetts'")
```

```{r, echo=FALSE, include=FALSE, message=FALSE, results=FALSE, warning=FALSE}
daily_report
```

## Interactive Graphs
```{r, fig.width = 5, fig.height = 5, echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)
ggplotly(
  ggplot(data = ma_county, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(data = state_join, aes(fill = Confirmed), color = "black") +
    scale_fill_gradientn(colours = 
                         wes_palette("Zissou1", 100, type = "continuous")) +
  ggtitle("COVID-19 Cases in MA") +
# Cleaning up the graph
  labs(x=NULL, y=NULL) +
  theme(panel.border = element_blank()) +
  theme(panel.background = element_blank()) +
  theme(axis.ticks = element_blank()) +
  theme(axis.text = element_blank())
)
```

## Exercises
```{r, echo=FALSE, message=FALSE, results=FALSE, warning=FALSE}
# 1. 
daily_report_09_26 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-26-2020.csv")) %>% 
  rename(Long = "Long_") %>% 
  group_by(Country_Region, Long, Lat) %>% 
  filter(Lat !="NA") %>%
  filter(Long != "NA") %>% 
  summarise(Confirmed = sum(Confirmed))


ggplotly(
ggplot(data = daily_report_09_26,aes(x = Long, y = Lat, size = Confirmed/100000)) +
  borders("world", color = NA, fill = "grey20") +
  theme_bw() +
  geom_point(shape = 10, color = "green", fill = "green", alpha = 0.3) +
  labs(title = "World COVID-19 Confirmed Cases on 9/26/2020", x = "Long", y = "Lat", size = "Cases (x100000)") +
  theme(legend.position =  "bottom") +
  coord_fixed(ratio = 1.5)
)
```

```{r, echo=FALSE, message=FALSE, results=FALSE, warning=FALSE}
## 2. 
daily_report_09_26 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-26-2020.csv")) %>% 
  rename(Long = "Long_") %>% 
  filter(Country_Region == "US") %>% 
  filter (!Province_State %in% c("Alaska","Hawaii", "American Samoa","Puerto Rico","Northern Mariana Islands", "Virgin Islands", "Recovered", "Guam", "Grand Princess", "District of Columbia", "Diamond Princess")) %>% 
  filter(Lat > 0)
ggplot(daily_report_09_26, aes(x = Long, y = Lat, size = Confirmed/100000)) +
    borders("state", colour = "black", fill = "white") +
    theme_bw() +
    geom_point(shape = 21, color='magenta', fill='magenta', alpha = 0.3) +
    labs(title = 'COVID-19 Confirmed Cases in the US', x = 'Long', y = 'Lat',
        size="Cases (x100000))") +
    theme(legend.position = "right") +
    coord_fixed(ratio=1.5)

mybreaks <- c(1, 100, 1000, 10000, 10000)
ggplot(daily_report_09_26, aes(x = Long, y = Lat, size = Confirmed/100000)) +
    borders("state", colour = "white", fill = "grey90") +
    geom_point(aes(x=Long, y=Lat, size=Confirmed, color=Confirmed),stroke = F, alpha = 1, size = 2) +
    scale_size_continuous(name="Cases", trans="log", range=c(1,7), breaks=mybreaks, labels = c("1-99", "100-999", "1,000-9,999", "10,000-99,999", "50,000+")) +
scale_color_viridis_c(option="viridis",name="Cases", trans="log", breaks=mybreaks, labels = c("1-99", "100-999", "1,000-9,999", "10,000-99,999", "50,000+"))  +
theme_void() + 
    guides( colour = guide_legend()) +
    labs(title = "Anisa Dhana's lagout for COVID-19 Confirmed Cases in the US for 09/26/2020") +
    theme(
      legend.position = "bottom",
      text = element_text(color = "#22211d"),
      plot.background = element_rect(fill = "#ffffff", color = NA), 
      panel.background = element_rect(fill = "#ffffff", color = NA), 
      legend.background = element_rect(fill = "#ffffff", color = NA)
    ) +
    coord_fixed(ratio=1.3)
```

```{r,echo=FALSE, message=FALSE, results=FALSE, warning=FALSE}
## 3.
report_09_26_2020 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-26-2020.csv")) %>% 
  rename(Long = "Long_") %>% 
  unite(Key, Admin2, Province_State, sep = ".") %>% 
  group_by(Key) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  mutate(Key = tolower(Key))
dim(report_09_26_2020)

us_map_9_26 <- map_data("state")
counties <- map_data("county") %>% 
  unite(Key, subregion, region, sep = ".", remove = FALSE)

state_join_9_26 <- left_join(counties, report_09_26_2020, by = c("Key"))
sum(is.na(state_join_9_26$Confirmed))
```
```{r, fig.width = 5, fig.height = 5, echo=FALSE, message=FALSE, results=FALSE, warning=FALSE}
ggplot(data = us_map_9_26, mapping = aes(x = long, y = lat, group = group)) +
  coord_fixed(1.3) +
  borders("state", color = "black") +
  geom_polygon(data = state_join_9_26, aes(fill = Confirmed)) +
  scale_fill_gradientn(colors = brewer.pal(n = 5, name = "PRGn"), breaks = c(1, 10, 100, 1000, 10000, 100000, 1000000), trans = "log10", na.value = "white") +
  ggtitle("Confirmed Cases of COVID-19 by US County on 09/26/2020 ") +
  theme_classic()
```

```{r, echo=FALSE, message=FALSE, results=FALSE, warning=FALSE}
## 4.
daily_report_AL <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-26-2020.csv")) %>% 
  rename(Long = "Long_") %>% 
  filter(Province_State == "Alabama") %>% 
  group_by(Admin2) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  mutate(Admin2 = tolower(Admin2))
us <- map_data("state")
al_us <- subset(us, region == "alabama")
counties <- map_data("county")
al_county <- subset(counties, region == "alabama")
state_join_AL <- left_join(al_county, daily_report_AL, by = c("subregion" = "Admin2")) 

ggplot(data = al_county, mapping = aes(x = long, y = lat, group = group)) +
  coord_fixed(1.3) +
  geom_polygon(data = state_join_AL, aes(fill = Confirmed), color = "white") +
  scale_fill_gradientn(colors = brewer.pal(n = 5, name = "Reds"), trans = "log10") +
  labs(title = "COVID-19 Confirmed in Alabama")
```

```{r, fig.width = 5, fig.height = 5, echo=FALSE, message=FALSE, results=FALSE, warning=FALSE}
ggplotly(
  ggplot(data = al_county, mapping = aes(x = long, y = lat, group = group)) +
    coord_fixed(1.3) +
    geom_polygon(data = state_join_AL, aes(fill = Confirmed), color = "black") +
    scale_fill_gradientn(colours = wes_palette("GrandBudapest2", 100, type = "continuous")) +
    ggtitle("COVID-19 Cases in Alabama") +
    labs(x = NULL, y = NULL) +
      theme(panel.border = element_blank()) +
  theme(panel.background = element_blank()) +
  theme(axis.ticks = element_blank()) +
  theme(axis.text = element_blank())
)
```

# REFERENCE
[@Dong2020]